CREATE TABLE devices (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT UNSIGNED NOT NULL,
    device_uuid VARCHAR(100) NOT NULL,
    name VARCHAR(150) NOT NULL,
    token_hash VARCHAR(255) NULL,
    group_id BIGINT UNSIGNED NULL,
    location VARCHAR(255) NULL,
    orientation ENUM('LANDSCAPE', 'PORTRAIT') DEFAULT 'LANDSCAPE',
    resolution_width INT NULL,
    resolution_height INT NULL,
    os VARCHAR(100) NULL,
    player_version VARCHAR(50) NULL,
    status ENUM('ONLINE', 'DEGRADED', 'OFFLINE') DEFAULT 'OFFLINE',
    last_seen_at DATETIME NULL,
    last_sync_at DATETIME NULL,
    current_manifest_version BIGINT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_device_uuid (device_uuid),
    INDEX idx_devices_tenant (tenant_id),
    INDEX idx_devices_last_seen (last_seen_at),
    INDEX idx_devices_group (group_id)
);
